# -*- coding: utf-8 -*-
"""StockAnalyzer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_RCgn6EIW9VD-iLhV7wEWZ8csSPe9i3m
"""

import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from bs4 import BeautifulSoup
import lxml

!pip install bsedata

from bsedata.bse import BSE
b=BSE()
data = pd.DataFrame(b.getQuote('534976'))

from google.colab import drive
drive.mount('/content/drive')

bsestocks=pd.read_csv('/content/drive/MyDrive/BSE_StockList.csv')
bsestocks.head()

bsestocks.drop(columns=['Issuer Name'], axis=1, inplace=True)

bsestocks.info()

d3=bsestocks.head(5)

cols= ['companyName', 'currentValue', 'change', 'pChange', 'updatedOn',
       'priceBand', 'securityID', 'scripCode', 'group', 'faceValue',
       'industry', 'previousClose', 'previousOpen', 'dayHigh', 'dayLow',
       '52weekHigh', '52weekLow', 'weightedAvgPrice', 'totalTradedValue',
       'totalTradedQuantity', '2WeekAvgQuantity', 'marketCapFull',
       'marketCapFreeFloat', 'upperPriceBand', 'lowerPriceBand', 'buy', 'sell',
       'StockCode']
masterData=pd.DataFrame(columns=cols)
for idx, sc in enumerate(d3['Security Code']):
  print("Stock Code: {}".format(sc))
  print("*"*60)
  d1 = pd.DataFrame(b.getPeriodTrend(str(sc),'3M'))
  d1['StockCode']=sc 
  print(d1)

print(b.getQuote('500354'))
